const express = require('express')
const router = express.Router()
const admin = require('./modules/admin')
const restController = require('../../controllers/apis/restaurant-controller')
const userController = require('../../controllers/apis/user-controller')
const orderController = require('../../controllers/apis/order-controller')
const { authenticated, authenticatedAdmin } = require('../../middleware/api-auth')
const { apiErrorHandler } = require('../../middleware/error-handler')
const upload = require('../../middleware/multer')
router.get('/get_current_user', authenticated, userController.getCurrentUser)
router.put('/users', upload.single('image'), authenticated, userController.putUser)
router.use('/admin', authenticated, authenticatedAdmin, admin)
router.post('/signup', userController.signUp)
router.post('/signin', userController.signIn)
router.get('/order/:id', authenticated, orderController.getOrder)
router.put('/order', authenticated, orderController.putOrder)
router.get('/searchList', authenticated, restController.getSearch)
router.post('/address', authenticated, restController.postAddress)
router.get('/address/:id', authenticated, restController.getAddress)
router.get('/restaurants/:id', authenticated, restController.getRestaurant)
router.get('/restaurants', authenticated, restController.getRestaurants)
router.use('/', apiErrorHandler)
module.exports = router
